### ISSUE TITLE
docs links are broken

### ISSUE THREAD

**Issue by ViralBShah** [JuliaGeometry/DistMesh.jl#24]

**Comment by sjkelly** [comment]
I put a link to my technical report in the README that documents the differences with the original algorithm (distance caching, Hilbert sorting, and nonlinear displacement).

https://sjkellyorg.files.wordpress.com/2020/11/distmesh_sjkelly.pdf

May be some time before I can spend some time here. Your interest is a strong motivator through :).

**Comment by ViralBShah** [comment]
Per-Olof, the author of the original `distmesh` is a good friend, and I was just talking with him and @ChrisRackauckas the other day about rounding out more of Julia's finite element and PDE Capabilities. Distmesh was an obvious first starting point, and I searched and found this package. :-)

I think it could make its way into a lot of things in the Julia ecosystem.

**Comment by ViralBShah** [comment]
I learnt a lot about what a system like Julia should contain from Per-Olof, and it is great that he is teaching a fantastic Julia class at Berkeley now: http://persson.berkeley.edu/math124/

**Comment by ViralBShah** [comment]
Thanks for the link to the thesis. Enjoying flipping through it.
